/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LocalSeoRouteImport } from './routes/local-seo'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as WebDesignRouteImport } from './routes/web-design'
import { Route as AutomationIndexRouteImport } from './routes/automation.index'
import { Route as AutomationSlugRouteImport } from './routes/automation.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSeoRoute = LocalSeoRouteImport.update({
  id: '/local-seo',
  path: '/local-seo',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const WebDesignRoute = WebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIndexRoute = AutomationIndexRouteImport.update({
  id: '/automation/',
  path: '/automation/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationSlugRoute = AutomationSlugRouteImport.update({
  id: '/automation/$slug',
  path: '/automation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/local-seo': typeof LocalSeoRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/web-design': typeof WebDesignRoute
  '/automation/$slug': typeof AutomationSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/automation/': typeof AutomationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/local-seo': typeof LocalSeoRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/web-design': typeof WebDesignRoute
  '/automation/$slug': typeof AutomationSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/automation': typeof AutomationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/local-seo': typeof LocalSeoRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRoute
  '/web-design': typeof WebDesignRoute
  '/automation/$slug': typeof AutomationSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/automation/': typeof AutomationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/local-seo'
    | '/pricing'
    | '/services'
    | '/web-design'
    | '/automation/$slug'
    | '/industries/$slug'
    | '/automation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/local-seo'
    | '/pricing'
    | '/services'
    | '/web-design'
    | '/automation/$slug'
    | '/industries/$slug'
    | '/automation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/local-seo'
    | '/pricing'
    | '/services'
    | '/web-design'
    | '/automation/$slug'
    | '/industries/$slug'
    | '/automation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LocalSeoRoute: typeof LocalSeoRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRoute
  WebDesignRoute: typeof WebDesignRoute
  AutomationSlugRoute: typeof AutomationSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  AutomationIndexRoute: typeof AutomationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-seo': {
      id: '/local-seo'
      path: '/local-seo'
      fullPath: '/local-seo'
      preLoaderRoute: typeof LocalSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/web-design': {
      id: '/web-design'
      path: '/web-design'
      fullPath: '/web-design'
      preLoaderRoute: typeof WebDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/': {
      id: '/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AutomationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/$slug': {
      id: '/automation/$slug'
      path: '/automation/$slug'
      fullPath: '/automation/$slug'
      preLoaderRoute: typeof AutomationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LocalSeoRoute: LocalSeoRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRoute,
  WebDesignRoute: WebDesignRoute,
  AutomationSlugRoute: AutomationSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  AutomationIndexRoute: AutomationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
